### ISSUE TITLE
 HTTP calls using protojson demo error

### ISSUE THREAD

**Issue by feeops** [shenzhencenter/google-ads-pb#33]
![image](https://github.com/user-attachments/assets/1e5bb8ce-d8e8-4182-9663-83c8fb4bf68c)

**Comment by xnkjj** [comment]
Fixed in the latest [PR](https://github.com/shenzhencenter/google-ads-pb/commit/58644c958bbf4e3f22209885df22c3f60d609516#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L124)

Thank you, @feeops, for pointing out the incorrect variable in the README. I sincerely apologize for the oversight, and I’m happy to inform you that the issue has now been corrected.
